zsh fine tuning

diff --git a/files/zshrc b/files/zshrc
--- a/files/zshrc
+++ b/files/zshrc
@@ -1,18 +1,17 @@
-# zsh variables
+### zsh variables ###
 HISTFILE=~/.histfile
 HISTSIZE=1000
 SAVEHIST=1000
 DIRSTACKSIZE=8
 KEYTIMEOUT=1
 
-
-# zsh base configuration
-setopt appendhistory # no history overwriting
-setopt autopushd pushdminus pushdsilent pushdtohome
-set -o vi
+# color aliases
+light_blue=27
+dark_red=124
 
 
-# setup antigen
+
+### setup antigen ###
 if [[ -f "${HOME}/.antigen.zsh" ]]
 then
     source ${HOME}/.antigen.zsh
@@ -23,16 +22,17 @@ then
 fi
 
 
-# autoloads
-# completion is autoloaded by antigen apply
-autoload -U colors && colors
+### autoloads ###
+# completion is autoloaded by 'antigen apply'
+autoload colors && colors
+autoload zkbd # for correct key functionalities
 autoload -U vcs_info # for git info on prompt
 autoload -U up-line-or-beginning-search   # both here are for
 autoload -U down-line-or-beginning-search # better history search
 
 
-# function defs
-git_color() {
+### function defs ###
+function git_color {
     if ! which git > /dev/null 2>&1
     then
         return
@@ -53,37 +53,34 @@ git_color() {
     echo 'green'
 }
 
-
-# setup completion
-zstyle ':completion:*' insert-unambiguous true
-zstyle ':completion:*' insert-tab false
-zstyle ':completion:*' menu select
-zstyle :compinstall filename "${HOME}/.zshrc"
-
-
-# setup left prompt
-# user:host dir $
-
 # hooks for populating the "vim_mode" variable so we can change the
 # prompt color accordingly
-light_blue=27
-dark_red=124
-
 function zle-line-init {
     vim_mode="${${KEYMAP/vicmd/${dark_red}}/(main|viins)/${light_blue}}"
     zle reset-prompt
 }
+
 function zle-keymap-select {
     zle-line-init
 }
 
+
+### setup left prompt ###
+# will look like (except colors):
+# user:host dir ▶
+
+# set hooks in place
 zle -N zle-keymap-select
 zle -N zle-line-init
 
 # populate prompt
 PROMPT='%B%F{${light_blue}}%n%f:%F{${light_blue}}%m%f %c %F{${vim_mode}}▶%f%b '
 
-# setup right prompt
+
+## setup right prompt ##
+# will show git info as
+# (branch_name)
+# and color-code the staging area status
 setopt prompt_subst
 zstyle ':vcs_info:*' action_formats '%b|%a'
 zstyle ':vcs_info:*' formats '%b'
@@ -98,21 +95,68 @@ precmd() {
 }
 
 
-# setup history search
+### be compatible with any terminal emulator ###
+function zkbd_file() {
+    [[ -f ~/.zkbd/${TERM}-${VENDOR}-${OSTYPE} ]] && printf '%s' ~/".zkbd/${TERM}-${VENDOR}-${OSTYPE}" && return 0
+    [[ -f ~/.zkbd/${TERM}-${DISPLAY}          ]] && printf '%s' ~/".zkbd/${TERM}-${DISPLAY}"          && return 0
+    return 1
+}
+
+# try to find zkbd file for current terminal
+keyfile=$(zkbd_file)
+ret=$?
+
+# if not found, run zkbd to create it and then grab it
+if [[ ${ret} -ne 0 ]]; then
+    zkbd
+    keyfile=$(zkbd_file)
+    ret=$?
+fi
+
+# source the result or warn for failure
+if [[ ${ret} -eq 0 ]] ; then
+    source "${keyfile}"
+else
+    printf 'Failed to setup keys using zkbd.\n'
+fi
+
+# unset stuff
+unfunction zkbd_file; unset keyfile ret
+
+# use history backwards search on up and down
 zle -N up-line-or-beginning-search
 zle -N down-line-or-beginning-search
-bindkey "^[[A" up-line-or-beginning-search
-bindkey "^[[B" down-line-or-beginning-search
+
+# setup keys accordingly
+[[ -n "${key[Home]}"    ]]  && bindkey  "${key[Home]}"    beginning-of-line
+[[ -n "${key[End]}"     ]]  && bindkey  "${key[End]}"     end-of-line
+[[ -n "${key[Insert]}"  ]]  && bindkey  "${key[Insert]}"  overwrite-mode
+[[ -n "${key[Delete]}"  ]]  && bindkey  "${key[Delete]}"  delete-char
+[[ -n "${key[Up]}"      ]]  && bindkey  "${key[Up]}"      up-line-or-beginning-search
+[[ -n "${key[Down]}"    ]]  && bindkey  "${key[Down]}"    down-line-or-beginning-search
+[[ -n "${key[Left]}"    ]]  && bindkey  "${key[Left]}"    backward-char
+[[ -n "${key[Right]}"   ]]  && bindkey  "${key[Right]}"   forward-char
 
 
-# aliases
-alias ls='ls --color'
+### zsh usability configurations ###
+setopt appendhistory # no history overwriting
+setopt autopushd pushdminus pushdsilent pushdtohome
+set -o vi
 
 # eval dircolors if possible
-
 COLORFILE=${HOME}/.dir_colors
-[[ -f ${COLORFILE} && $(tput colors) == 256 ]] && which dircolors > /dev/null && eval $(dircolors ${COLORFILE})
+[[ -e ${COLORFILE} && $(tput colors) == 256 ]] && which dircolors > /dev/null && eval $(dircolors ${COLORFILE})
 
+# setup completion
+zstyle ':completion:*' insert-unambiguous true
+zstyle ':completion:*' insert-tab false
+zstyle ':completion:*' menu select
+zstyle ':completion:*' list-colors "${(@s.:.)LS_COLORS}"
+zstyle :compinstall filename "${HOME}/.zshrc"
+setopt complete_aliases # do not expand aliases before completion
+
+# aliases
+alias ls='ls -F --color'
 
 # source local definitions if any
 [[ -f ${HOME}/.zshrc_local ]] && source ${HOME}/.zshrc_local
